  build:
    needs: test
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.9"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 nuitka
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Clean previous build
      run: Remove-Item -Recurse -Force build

    - name: Build with Nuitka
      run: python -m nuitka main.py --standalone --mingw64 --enable-plugin=pyqt5 --output-dir=build --assume-yes-for-download --lto=yes

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pyqt5-app
        path: build/main.exe
